### ISSUE TITLE
vtGBte tile editor

### ISSUE THREAD

**Issue by paul-arutyunov** [gbdev/awesome-gbdev#122]
vtGBte - A raw-binary format tile editor for Unix systems.

What I'm supposed to write here?

**Comment by paul-arutyunov** [comment]
Oh, yeah. Something like "vtGBte - A pseudo graphical interface-based raw-binary format tile editor for Unix systems."
A little bit too much text

**Comment by paul-arutyunov** [comment]
We can go with "vtGBte - A non-GUI raw binary-format tile editor for Unix systems."

**Comment by avivace** [comment]
I don't think that the fact it saves in binary format is relevant, since it's a common (and anyway, _expected_) feature. Also, the standard _is_ Unix. The problem/marginal cases are Windows-only softwares, for which we specify things like "runs in Wine" (e.g. the BGB emulator).

Something like "vtGBte - A cross platform tile editor running in the terminal" or - since ncurses is pretty popular among developers - "vtGBte - ncurses tile editor"

**Comment by paul-arutyunov** [comment]
Maybe "vtGBte - A minimalistic ncurses tile editor"?

**Comment by avivace** [comment]
Doesn't having a CLI interface / being developed in ncurses already imply it's minimalistic?

**Comment by paul-arutyunov** [comment]
Haha
It's also pretty small - no other libs, not very much of code
'd like to emphasize that.

**Comment by avivace** [comment]
Dependency free (actually it depends on ncurses)? Or simply, CLI tool..

**Comment by paul-arutyunov** [comment]
It definitely wouldn't work without ncurses, so I guess it depends on ncurses

**Comment by paul-arutyunov** [comment]
I mean, it's GUI-like
Pseudo graphic

**Comment by paul-arutyunov** [comment]
Created PR
