### ISSUE TITLE
List Review: (3) Documentation

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#161]
See #158 for context

> 1. **[Game Boy Programming Manual](https://archive.org/download/GameBoyProgManVer1.1/GameBoyProgManVer1.1.pdf)** - Official Game Boy programming and hardware manual by Nintendo.
> 2. [Pan Docs](http://gbdev.gg8.se/wiki/articles/Pan_Docs) - Historical comprehensive technical reference, wikified, corrected and updated.
> 3. [The Cycle-Accurate Game Boy Docs](https://github.com/AntonioND/giibiiadvance/blob/master/docs/TCAGBD.pdf) - A precise documentation by AntonioND to make a cycle-accurate Game Boy emulator.
> 4. [Game Boy: Complete Technical Reference](https://gekkio.fi/files/gb-docs/gbctr.pdf) by Gekkio.

**Comment by ISSOtm** [comment]
1. Keep. We keep finding new things in it; also, historical value
2. Change to the new version?
3. Isn't it superseded by other documents?
4. Keep.

**Comment by avivace** [comment]
3. Which document (a part from GBCTR) supersedes that?

**Comment by NieDzejkob** [comment]
1. Keep, but mention that despite being official, the docs are sub-par and have mostly historical value.

**Comment by avivace** [comment]
@NieDzejkob sub-par to what? What other documentation are you thinking of?

**Comment by ISSOtm** [comment]
In readability and depth.

**Comment by NieDzejkob** [comment]
@avivace Pan Docs & the opcode table go a long way. There's also `man 7 gbz80` from rgbds.

**Comment by avivace** [comment]
Semi unrelated: Diagrams from that manual are really good. I've started to port some of them on pan docs.

**Comment by aaaaaa123456789** [comment]
1: agreed with above; if you're keeping it here and not moving it to the beginning of the list, mention that it's mostly there for its historical value and not a good reference
2: replace with the new wiki link. I'd still point to the old document, too (not the wiki, but the actual document), because it's been the canonical reference for ages and people would probably still want to be able to find it quickly.
3, 4: not too sure about the quality of these documents; they seem well made, but also outdated. Someone should probably review them.

**Comment by ISSOtm** [comment]
What would have outdated gb-ctr?
