### ISSUE TITLE
List Review: (4) Documentation > Misc

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#162]
See #158 for context

> 
> 1 - [Introduction to Game Boy Hacking](http://pepijndevos.nl/sha2017/workshop.pdf) - Workshop introducing basic assembly, debugging and reverse engineering.
> 2 - [Everything You Always Wanted To Know About GAME BOY](http://www.emulatronia.com/doctec/consolas/gameboy/gameboy.txt) - but were afraid to ask
> 3 - [GBSOUND.txt](https://github.com/bwhitman/pushpin/blob/master/src/gbsound.txt) - A document detailing the Game Boy sound engine.
> 4 - [GB Instructions](https://raw.githubusercontent.com/gb-archive/salvage/master/txt-files/gb-instructions.txt) Game Boy Assembly commands.
> 5 - [GB ASM Tips](https://raw.githubusercontent.com/gb-archive/salvage/master/txt-files/gb-asm-tips.txt) - Some tips for coding in Assembly by Jeff Frohwein.
> 6 - [gbdev FAQs](http://www.devrs.com/gb/files/faqs.html) - Must read by Jeff Frohwein.
> 7 - [Game Boy Bootrom](http://www.neviksti.com/DMG/DMG_ROM.asm) - Commented dump of the DMG bootrom.
> 8 - [GB Technical Information](http://fms.komkon.org/GameBoy/Tech/) - Some old code resources.
> 9 - [Differences between the Z80 and the gameboy's processor](http://www.z80.info/z80gboy.txt)
> 10 - [Gameboy 2BPP Graphics Format](http://www.huderlem.com/demos/gameboy2bpp.html) - Information on how the Game Boy interprets VRAM tile data to color pixels.

**Comment by avivace** [comment]
Okay, this is gonna be long.

1. Keep
2. Remove. This is an old version of Pan Docs.
3. Move to a Sound section. Do we have an updated document with a similar scope? Should we move that in the Pan Docs as "side tutorial"?
4. Move. This is more related to ASM programming than a general documentation resource
5. Same as 4.
6. Outdated, but we need an updated FAQ document.
7. Move. Not sure where, but I don't the the utility of having the bootrom as a Documentation resource.
8. Move. THis is a directory of old resources, not sure if there's something we'd want to link directly.
9. There's a chapter of Pan Docs covering this. Check if all the information is there and in case directly link that chapter.
10. Move to a chapter dedicated to Video?

11. Miscellanea/uncategorized should be the last section, or anyway not at the top.

**Comment by ISSOtm** [comment]
1. Mixed opinion. It's good, but outdated (refers to a much earlier state of the disassembly, it has improved a lot since then. Not sure the constants it's referring to haven't changed names since; if that's the case, I'm for removal unless it gets updated)
2. Delet
3. Not sure either. The format isn't great, and a lot of the info is now covered by Pan Docs. Plus there are typographical and grammatical errors (plus a `.txt` file that was clearly intended to be read with a certain viewport size) that hinder comprehension.
4. Agree to move, but it's superseded by [gbz80(7)](https://rednex.github.io/rgbds/gbz80.7.html) anyways.
5. Keep & move.
6. Some parts are severely outdated, other parts are still good and relevant. Against keeping it as-is, but it'd be a good idea to make a copy with some sections (such as those about official devkits) elided.
7. Superseded by [gb-bootroms](https://github.com/ISSOtm/gb-bootroms). Relevant both to emulator devs and as historical info, so I think it fits a misc section.
8. Outdated.
9. Same. Might be worth porting to Pan Docs with attribution if it's incomplete in the current docs.
10. Good as a general resource to emulator devs and all programmers. Create a "technical references" section maybe?
11. Yep.
