### ISSUE TITLE
Game Boy Advance

### ISSUE THREAD

**Issue by avivace** [gbdev/awesome-gbdev#164]
- Mention somewhere (maybe in the "disambiguation" box?) that GBA is a completely difference story, not covered here. Link to awesome-gbadev.
- Describe the intersection of GBA and GB/GBC: GBA running on CGB mode (different colors, different registers init, APU quirks). Maybe @LIJI32 or @endrift can describe this briefly (or point me to some documentation describing GBA in CGB mode) ?

**Comment by LIJI32** [comment]
Differences between CGB-E, which the AGB's CGB core is based on, and AGB include:
- The removal of the IR port
- The LCD's color space and grey curves are different
- Audio mixing is done differently and is completely digital on the AGB; the AGB emulates the CGB's DACs as if they're always on
- Channel 3's output is inverted on the AGB
- Slightly different boot ROM, register B is 1 instead of 0 on start up. Timings are also different.

As far as I can tell, there are no other differences.

**Comment by avivace** [comment]
Clear! Thank you. I'll leave this open for a while in case anyone wants to add something.
