### ISSUE TITLE
Wrong opcode length in linked cheatsheet

### ISSUE THREAD

**Issue by trakons** [gbdev/awesome-gbdev#172]
The linked resource [OP Codes cheatsheet](https://pastraiser.com/cpu/gameboy/gameboy_opcodes.html)  
Contains wrong byte length at instructions `0xE2` and `0xF2`, both show 2 instead of 1.

**Comment by ISSOtm** [comment]
Considering we have the [community-maintained](https://github.com/gbdev/gb-opcodes) [updated tables](https://gbdev.github.io/gb-opcodes/optables/classic) [right below](https://github.com/gbdev/awesome-gbdev#cheatsheets-tables), shouldn't the pastraiser link be removed altogether? Since the new version *does* link to old one...
