### ISSUE TITLE
would like to add an sgb border tutorial

### ISSUE THREAD

**Issue by zlago** [gbdev/awesome-gbdev#246]
- i have no idea how to do this!
- all feedback is welcome, i probably overlooked something
- if anything needs to be changed, ill see what i can do
- any help, whether it be merging this, or helping me open a PR, is welcome
- the document has a clear purpose, hopefully it also does its job reasonably
- if this is the wrong place for it, please redirect me
- if use of proper grammar is required within the document, i will see if i have enough motivation to change everything

~~[file](https://github.com/gbdev/awesome-gbdev/files/12072548/border.md)~~ [gist](https://gist.github.com/zlago/f8cb9bc1717eda7912580753d04b52c0)

**Comment by aaaaaa123456789** [comment]
gist.github.com will offer you a nice place to place the file so we can see it without downloading. It also lets you edit it.

**Comment by avivace** [comment]
Hey, thanks a lot for the contribution!
Maybe we could think about adding the guide directly on gbdev.io with the other "Guides"?

Would you be able to start a PR there adding the md file under https://github.com/gbdev/gbdev.github.io/tree/dev/website/guides ? Otherwise I'll gladly help/guide you there
